CREATE TABLE MODELO
(
    ID                     INT NOT NULL,
    NOME                   VARCHAR(45)  NOT NULL,
    CAPACIDADE_COMBUSTIVEL INT NOT NULL
);

ALTER TABLE MODELO
    ADD CONSTRAINT UNIQUE_MODELO UNIQUE (NOME);
ALTER TABLE MODELO
    ADD CONSTRAINT PK_MODELO PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_MODELO
    INCREMENT BY 1
    START WITH 1;

CREATE TABLE VEICULO
(
    ID        INT NOT NULL,
    PLACA     VARCHAR(8)   NOT NULL,
    MODELO_ID INT NOT NULL,
    PRIMARY KEY (ID),

    CONSTRAINT Fk_VEICULO_MODELO
        FOREIGN KEY (MODELO_ID)
            REFERENCES MODELO (ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);
CREATE SEQUENCE SEQ_VEICULO
    INCREMENT BY 1
    START WITH 1;

CREATE TABLE COMBUSTIVEL
(
    ID   INT NOT NULL,
    TIPO VARCHAR(45)  NOT NULL,
    PRIMARY KEY (ID)
    );

CREATE SEQUENCE SEQ_COMBUSTIVEL
    INCREMENT BY 1
    START WITH 1;

ALTER TABLE COMBUSTIVEL
    ADD CONSTRAINT UNIQUE_TIPO UNIQUE (TIPO);

CREATE TABLE COMBUSTIVEL_MODELO
(
    ID             INT NOT NULL,
    CONSUMO        INT NOT NULL,
    MODELO_ID      INT NOT NULL,
    COMBUSTIVEL_ID INT NOT NULL,
    PRIMARY KEY (ID),

    CONSTRAINT FK_COMBUSTIVEL_MODELO_MODELO1
    FOREIGN KEY (MODELO_ID)
    REFERENCES MODELO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    CONSTRAINT FK_COMBUSTIVEL_MODELO_COMBUSTIVEL1
    FOREIGN KEY (COMBUSTIVEL_ID)
    REFERENCES COMBUSTIVEL (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );

CREATE SEQUENCE SEQ_COMBUSTIVEL_MODELO
    INCREMENT BY 1
    START WITH 1;

INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'FIAT-UNO',48);
INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'FORD-KA',55);
INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'CITROEN-C3',47);
INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'RENAULT-CLIO',50);
INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'AUDI-A1',45);
INSERT INTO MODELO(ID, NOME, CAPACIDADE_COMBUSTIVEL) VALUES (SEQ_MODELO.nextval, 'AUDI-A4',65);

INSERT INTO COMBUSTIVEL(ID, TIPO) VALUES (SEQ_COMBUSTIVEL.nextval, 'Etanol');
INSERT INTO COMBUSTIVEL(ID, TIPO) VALUES (SEQ_COMBUSTIVEL.nextval, 'Gasolina');

INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 8.9, 1, 1);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 8.1, 1, 2);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 7.5, 1, 3);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 9.5, 1, 4);

INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 12.7, 2, 1);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 11.6, 2, 2);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 11.9, 2, 3);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 14.3, 2, 4);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 10.8, 2, 5);
INSERT INTO COMBUSTIVEL_MODELO(ID, CONSUMO, COMBUSTIVEL_ID, MODELO_ID) VALUES(SEQ_COMBUSTIVEL_MODELO.nextval, 8.8, 2, 6);

INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGG-7389', 1);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGF-8573', 2);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGE-0620', 5);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JWM-1235', 3);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'KRM-6771', 4);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGE-4583', 5);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGE-9393', 2);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGE-0611', 4);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JHM-7491', 3);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JGM-4773', 2);
INSERT INTO VEICULO(ID, PLACA, MODELO_ID) VALUES(SEQ_VEICULO.nextval, 'JMM-7513', 6);

COMMIT;

